name: Build & Publish to Dynamis

on:
  push:
    tags:
      - 'v*.*'

jobs:
  Build:
    runs-on: ubuntu-latest
    env:
        DALAMUD_HOME: /tmp/dalamud
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: Get Tag Name
        run: echo "tag=$(echo ${{ github.ref }} | sed 's/refs\/tags\/v//')" >> $GITHUB_ENV

      - name: Set up .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 9.0.x
          
      - name: Get Latest Track
        id: latest_track
        uses: mikefarah/yq@master
        with:
            cmd: |
                yaml=$(wget -q -O- https://raw.githubusercontent.com/goatcorp/dalamud-declarative/main/config.yaml)
                versions=$(echo "$yaml" | yq '.tracks[] | .applicableGameVersion')
                sorted_versions=$(echo "$versions" | sort -r)
                highest_version=$(echo "$sorted_versions" | head -1)
                result=$(echo "$yaml" | yq '.tracks | to_entries | map(select(.value.applicableGameVersion == "$highest_version")) | sort_by(.key) | .[0].key')
                echo "${result}" >> $GITHUB_OUTPUT

      - name: Download Dalamud Latest
        run: |
          wget https://goatcorp.github.io/dalamud-distrib/${{ steps.latest_track.outputs.result }}/latest.zip -O ${{ env.DALAMUD_HOME }}.zip
          unzip ${{ env.DALAMUD_HOME }}.zip -d ${{ env.DALAMUD_HOME }}

      - name: Restore Project
        run: dotnet restore

      - name: Build Project
        run: dotnet build --configuration Release Automaton/Automaton.csproj -p:AssemblyVersion=${{ env.tag }}

      - name: Publish Version
        uses: PunishXIV/dynamis-action@v1
        id: dynamis
        with:
          plugin_id: 34
          internal_name: "Automaton"
          version_number: ${{ env.tag }}
          path: "Automaton/bin/Release/Automaton/latest.zip"
          type: "latest"
          dalamud_version: "12"
        env:
          PUBLISHER_KEY: ${{ secrets.PUBLISHER_KEY }}
